### ISSUE TITLE
Save images locally

### ISSUE THREAD

**Issue by sangjunp4rk** [lcanderson/prj-rev-bwfs-dasmoto#2]
Try to save your images locally instead of adding a link. Saving images adds to the stability of your website because your website is not reliant on the link to be valid all the time. So next time, save all the images under resources/images/

https://github.com/lcanderson/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L14

**Comment by lcanderson** [comment]
This comment makes sense.  As I read the instruction, I thought we were _supposed_ to use the links for our pictures.  I will use locally stored pictures in the future.
