### ISSUE TITLE
Specify strong

### ISSUE THREAD

**Issue by sangjunp4rk** [lcanderson/prj-rev-bwfs-dasmoto#3]
Next time, make sure to specify your strong. For example, do `<strong class = “prices” >`. This makes your code more flexible as it grows in the future and you have to use strong elsewhere. This way you can use span elsewhere if you just specify another class.

https://github.com/lcanderson/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L26

**Comment by lcanderson** [comment]
Ah, very good tip.  Thank you!
